// Generated by Bract Compiler
// https://github.com/bract-lang/bract

void id_9(void) {
    id_0 Bract_symbol_10 = (id_0) { .id_1 = 3.0, .id_2 = 4.0 };
    id_0 Bract_symbol_11 = (id_0) { .id_1 = 0.0, .id_2 = 0.0 };
}

