// Generated by Bract Compiler
// https://github.com/bract-lang/bract

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Bract_runtime.h"

// Forward declarations
typedef struct main main;

struct main {
    int32_t add;
    int32_t subtract;
};

