// Generated by Bract Compiler
// https://github.com/bract-lang/bract

const double id_1 = 3.14159265359;

const double id_2 = 2.71828182846;

int32_t id_3(int32_t id_4, int32_t id_5) {
    return (id_4 + id_5);
}

double id_6(double id_7) {
    return ((id_1 * id_7) * id_7);
}

